# Generated by Django 4.2.4 on 2023-08-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('pageCount', models.PositiveIntegerField()),
                ('publishedDate', models.DateTimeField()),
                ('thumbnailUrl', models.URLField()),
                ('shortDescription', models.TextField()),
                ('longDescription', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('authors', models.ManyToManyField(to='app.author')),
                ('categories', models.ManyToManyField(to='app.category')),
            ],
        ),
    ]
